services:
  - type: web
    name: findora-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://findora-ai-lost-found.vercel.app
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: FROM_NAME
        value: Findora
    disk:
      name: findora-data
      mountPath: /data
      sizeGB: 1